[tool.poetry]
name = "aws-cryptographic-material-providers"
version = "0.1.0"
description = ""
authors = ["AWS <aws-arg-dafny@amazon.com>"]
packages = [
    { include = "aws_cryptography_keystore", from = "src" },
    { include = "aws_cryptography_materialproviders", from = "src" },
]
# Include all Smithy- and Dafny-generated code in package distributions,
# even though they are not included in version control
include = ["**/smithygenerated/*.py", "**/internaldafny/generated/*.py", "**/internaldafny/generated/**/*.py"]

[tool.poetry.dependencies]
python = "^3.11.0"
# TODO: Depend on PyPi once Smithy-Python publishes their Python package there
smithy-python = { path = "../../../../../submodules/smithy-python/python-packages/smithy-python", develop = false}
standard-library = { path = "../../../StandardLibrary/runtimes/python", develop = false}
amazon-cryptography-internal-dafny-shim-kms = {path = "../../../ComAmazonawsKms/runtimes/python", develop = false}
amazon-cryptography-internal-dafny-shim-ddb = {path = "../../../ComAmazonawsDynamodb/runtimes/python", develop = false}
mpl-internaldafny = { path = "src/aws_cryptography_materialproviders/internaldafny", develop = false}
mpl-externs = { path = "src/aws_cryptography_materialproviders/extern", develop = false}
keystore-internaldafny = { path = "src/aws_cryptography_keystore/internaldafny", develop = false}
aws-cryptography-primitives = {path = "../../../AwsCryptographyPrimitives/runtimes/python", develop = false}

[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
