# This workflow performs interoperability tests across the supported runtimes of the MPL.
name: Library Interoperability Tests

on:
  workflow_call:
    inputs:
      dafny:
        description: "The Dafny version to run"
        required: true
        type: string

jobs:
  generateEncryptVectors:
    strategy:
      matrix:
        library: [TestVectorsAwsCryptographicMaterialProviders]
        os: [
            # TODO just test on mac and ubuntu for now
            # windows-latest,
            ubuntu-latest,
            macos-latest,
          ]
        language: [java, net]
        dotnet-version: ["6.0.x"]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Support longpaths on Git checkout
        run: |
          git config --global core.longpaths true

      - uses: actions/checkout@v3
      # The specification submodule is private so we don't have access, but we don't need
      # it to verify the Dafny code. Instead we manually pull the submodule we DO need.
      - run: git submodule update --init libraries

      # Set up runtimes
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        if: ${{ matrix.language }} == 'net'
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Setup Java 17
        uses: actions/setup-java@v3
        if: ${{ matrix.language }} == 'java'
        with:
          distribution: "corretto"
          java-version: 17

      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1.6.1
        with:
          dafny-version: ${{ inputs.dafny }}

      # Build implementation for each runtime
      - name: Build ${{ matrix.library }} implementation in Java
        shell: bash
        working-directory: ./${{ matrix.library }}
        if: ${{ matrix.language }} == 'java'
        run: |
          # This works because `node` is installed by default on GHA runners
          CORES=$(node -e 'console.log(os.cpus().length)')
          make build_java CORES=$CORES

      - name: Build ${{ matrix.library }} implementation in .NET
        shell: bash
        working-directory: ./${{ matrix.library }}
        if: ${{ matrix.language }} == 'net'
        run: |
          # This works because `node` is installed by default on GHA runners
          CORES=$(node -e 'console.log(os.cpus().length)')
          make transpile_net

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
        if: ${{ matrix.language }} == 'java'
        with:
          gradle-version: 7.2

      # Test Vectors need to call KMS
      - name: Configure AWS Credentials for Tests
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::370957321024:role/GitHub-CI-MPL-Dafny-Role-us-west-2
          role-session-name: InterOpTests

      - name: Create Manifests
        working-directory: ./${{ matrix.library }}
        run: make test_generate_vectors_${{ matrix.language }}

      - name: Create Encrypt Manifests
        working-directory: ./${{ matrix.library }}
        run: make test_encrypt_vectors_${{ matrix.language }}

      - name: Upload Encrypt Manifest and keys.json files
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.os}}_vector_artifact_${{matrix.language}}
          path: ./${{matrix.library}}/runtimes/${{matrix.language}}/*.json

  testInteroperablity:
    needs: generateEncryptVectors
    strategy:
      matrix:
        library: [TestVectorsAwsCryptographicMaterialProviders]
        os: [
            # TODO just test on mac and ubuntu for now
            # windows-latest,
            ubuntu-latest,
            macos-latest,
          ]
        encrypting_language: [java, net]
        decrypting_language: [java, net]
        dotnet-version: ["6.0.x"]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Support longpaths on Git checkout
        run: |
          git config --global core.longpaths true
      # KMS and MPL tests need to use credentials which can call KMS
      - name: Configure AWS Credentials for Tests
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::370957321024:role/GitHub-CI-MPL-Dafny-Role-us-west-2
          role-session-name: InterOpTests

      - uses: actions/checkout@v3
      # The specification submodule is private so we don't have access, but we don't need
      # it to verify the Dafny code. Instead we manually pull the submodule we DO need.
      - run: git submodule update --init libraries

      # Set up runtimes
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        if: ${{ matrix.decrypting_language }} == 'net'
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Setup Java 17
        uses: actions/setup-java@v3
        if: ${{ matrix.decrypting_language }} == 'java'
        with:
          distribution: "corretto"
          java-version: 17

      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1.6.1
        with:
          dafny-version: ${{ inputs.dafny }}

      # Build implementation for each runtime
      - name: Build ${{ matrix.library }} implementation in Java
        shell: bash
        working-directory: ./${{ matrix.library }}
        if: ${{ matrix.decrypting_language }} == 'java'
        run: |
          # This works because `node` is installed by default on GHA runners
          CORES=$(node -e 'console.log(os.cpus().length)')
          make build_java CORES=$CORES

      - name: Build ${{ matrix.library }} implementation in .NET
        shell: bash
        working-directory: ./${{ matrix.library }}
        if: ${{ matrix.decrypting_language }} == 'net'
        run: |
          # This works because `node` is installed by default on GHA runners
          CORES=$(node -e 'console.log(os.cpus().length)')
          make transpile_net

      - name: Download Encrypt Manifest Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{matrix.os}}_vector_artifact_${{matrix.encrypting_language}}
          path: ./${{matrix.library}}/runtimes/${{matrix.encrypting_language}}

      - name: Decrypt Encrypt Manifest
        working-directory: ./${{ matrix.library }}
        run: make test_decrypt_encrypt_vectors_${{matrix.decrypting_language}}
