# This workflow performs interoperability tests across the supported runtimes of the MPL.
name: Library Interoperability Tests

on:
  workflow_call:
    inputs:
      dafny:
        description: "The Dafny version to run"
        required: true
        type: string

jobs:
  testInteroperablity:
    strategy:
      matrix:
        library: [TestVectorsAwsCryptographicMaterialProviders]
        os: [
            # TODO just test on mac and ubuntu for now
            # windows-latest,
            ubuntu-latest,
            macos-latest,
          ]
        dotnet-version: ["6.0.x"]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Support longpaths on Git checkout
        run: |
          git config --global core.longpaths true
      # KMS and MPL tests need to use credentials which can call KMS
      - name: Configure AWS Credentials for Tests
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::370957321024:role/GitHub-CI-MPL-Dafny-Role-us-west-2
          role-session-name: InterOpTests

      - uses: actions/checkout@v3
      # The specification submodule is private so we don't have access, but we don't need
      # it to verify the Dafny code. Instead we manually pull the submodule we DO need.
      - run: git submodule update --init libraries
      
      # Set up runtimes
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 17

      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1.6.1
        with:
          dafny-version: ${{ inputs.dafny }}

      # Build implementation for each runtime
      - name: Build ${{ matrix.library }} implementation in Java
        shell: bash
        working-directory: ./${{ matrix.library }}
        run: |
          # This works because `node` is installed by default on GHA runners
          CORES=$(node -e 'console.log(os.cpus().length)')
          make build_java CORES=$CORES

      - name: Build ${{ matrix.library }} implementation in .NET
        shell: bash
        working-directory: ./${{ matrix.library }}
        run: |
          # This works because `node` is installed by default on GHA runners
          CORES=$(node -e 'console.log(os.cpus().length)')
          make transpile_net
      
      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
        with:
            gradle-version: 7.2
     
      # Check that Java can continue to read its own produced manifest and hand it to .NET
      - name: Compile Java 17
        run: gradle -p ./${{ matrix.library }}/runtimes/java build

      - name: Create a manifest for Java to read and write
        run: gradle -p ./${{ matrix.library }}/runtimes/java run --args="encrypt-manifest --encrypt-manifest-output ."

      - name: Copy over keys.json so that it is discoverable by the CLI
        uses: gradle/gradle-build-action@v2
        with:
          arguments: copyKeysJSONCurr
          build-root-directory: ./${{ matrix.library }}/runtimes/java

      - name: Create encrypt manifest
        run: gradle -p ./${{ matrix.library }}/runtimes/java run --args="encrypt --manifest-path . --decrypt-manifest-path ."

      - name: Decrypt encrypt manifest
        run: gradle -p ./${{ matrix.library }}/runtimes/java run --args="decrypt --manifest-path ."

      - name: .NET decrypt Java's encrypt manifest
        working-directory: ./${{ matrix.library }}
        shell: bash
        run: |
            dotnet restore runtimes/net
            dotnet build runtimes/net
            dotnet run --project runtimes/net --framework net6.0 decrypt --manifest-path runtimes/java

    # Check that .NET can continue to read its own produced manifest and hand it to Java
      - name: .NET create manifest 
        working-directory: ./${{ matrix.library }}
        shell: bash
        run: |
            dotnet restore runtimes/net
            dotnet build runtimes/net
            dotnet run --project runtimes/net --framework net6.0 encrypt-manifest --encrypt-manifest-output runtimes/net
      
      - name: .NET encrypt manifest
        working-directory: ./${{ matrix.library }}
        shell: bash
        run: |
            dotnet run --project runtimes/net --framework net6.0 encrypt --manifest-path runtimes/net --decrypt-manifest-path runtimes/net
    
      - name: .NET decrypt encrypt manifest
        working-directory: ./${{ matrix.library }}
        shell: bash
        run: |
            dotnet run --project runtimes/net --framework net6.0 decrypt --manifest-path runtimes/net
    
      - name: Java Decrypt .NET's encrypt manifest
        run: gradle -p ./${{ matrix.library }}/runtimes/java run --args="decrypt --manifest-path ../net"

