# This workflow is triggered manually
name: MPL-Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "What version are you publishing"
        required: true
        type: string

jobs:
  getVersion:
    if: contains('["seebees","ShubhamChaturvedi7","lucasmcdonald3","josecorella","imabhichow","rishav-karanjit","antonf-amzn","justplaz","ajewellamz"]', github.actor)
    uses: ./.github/workflows/dafny_version.yaml
  # java-release:
  #   needs: getVersion
  #   uses: ./.github/workflows/java-release.yml
  #   with:
  #     dafny: ${{needs.getVersion.outputs.version}}
  #     version: ${{inputs.version}}