# This workflow is triggered manually
name: MPL-Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "What version are you publishing"
        required: true
        type: string

jobs:
  allowList:
    uses: ./.github/workflows/validate_user.yml
  getVersion:
    needs: [allowList]
    uses: ./.github/workflows/dafny_version.yaml
  getUniqueId:
    needs: [allowList]
    uses: ./.github/workflows/create_unique_id.yml
  java-release:
    needs: getVersion
    uses: ./.github/workflows/java-release.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}
      version: ${{inputs.version}}
  net-release:
    needs: [getVersion, getUniqueId]
    uses: ./.github/workflows/net-release.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}
      version: ${{inputs.version}}
      unique-id: ${{needs.getUniqueId.outputs.unique-id}}
