# This workflow is used to check if the user running the action
# is allowlisted
name: Validate User Permissions

on:
  workflow_call:

jobs:
  validateUser:
    runs-on: ubuntu-latest
    steps:
      - name: Is user allowlisted?
        id: allowList
        if: ${{ contains('["seebees","ShubhamChaturvedi7","texastony","lucasmcdonald3","josecorella","imabhichow","rishav-karanjit","antonf-amzn","justplaz","ajewellamz"]', github.actor)}}
        run: |
          echo "${{github.actor}} is allowed to run this action"
      - name: Error if blocklisted
        if: ${{steps.allowList.conclusion ==  'failure' || steps.allowList.conclusion == 'skipped'}}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('${{github.actor}} is not allow listed to run this workflow')
